# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PriceSource": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://rickatx.github.io/rfpfolio/"

git_url = "https://github.com/rickatx/rfpfolio/tree/master/"

def custom_doc_links(name): return None
