# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PriceSource": "00_core.ipynb",
         "PSeg": "00_core.ipynb",
         "SpliceSpec": "00_core.ipynb",
         "period_returns_from_prices": "00_core.ipynb",
         "cum_wr_to_period_returns": "00_core.ipynb",
         "pf_cum_wr_seq": "00_core.ipynb",
         "pf_period_returns": "00_core.ipynb",
         "computePortfolioReturns": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://rickatx.github.io/rfpfolio/"

git_url = "https://github.com/rickatx/rfpfolio/tree/master/"

def custom_doc_links(name): return None
